spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    username: super_admin
    password: SomeSecretPassword
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: "classpath:db/changelog/master.yml"
