spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    username: egor
    password: admin123
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: "classpath:db/changelog/master.yml"
server:
   port: 8096

logging:
  level:
    root: info

app:
  common:
    logging:
      enabled: true
      level: INFO